// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzKQKcnLqn96bowWj6WbAR-UtWaZS_5Dw',
    appId: '1:228604895992:web:1a2abad05381d3d2fe110d',
    messagingSenderId: '228604895992',
    projectId: 'coffeeshop-5cae5',
    authDomain: 'coffeeshop-5cae5.firebaseapp.com',
    storageBucket: 'coffeeshop-5cae5.firebasestorage.app',
    measurementId: 'G-TWY23P0XQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB31ZngYG-YRwyhF1WHW22mF8B-nC0_EqI',
    appId: '1:228604895992:android:4635495bb13c24eafe110d',
    messagingSenderId: '228604895992',
    projectId: 'coffeeshop-5cae5',
    storageBucket: 'coffeeshop-5cae5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDcyE8K2He-Fbll4vCQ8c-n_SwllaqmUc',
    appId: '1:228604895992:ios:c01275968de10a94fe110d',
    messagingSenderId: '228604895992',
    projectId: 'coffeeshop-5cae5',
    storageBucket: 'coffeeshop-5cae5.firebasestorage.app',
    iosBundleId: 'com.example.madProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDcyE8K2He-Fbll4vCQ8c-n_SwllaqmUc',
    appId: '1:228604895992:ios:c01275968de10a94fe110d',
    messagingSenderId: '228604895992',
    projectId: 'coffeeshop-5cae5',
    storageBucket: 'coffeeshop-5cae5.firebasestorage.app',
    iosBundleId: 'com.example.madProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzKQKcnLqn96bowWj6WbAR-UtWaZS_5Dw',
    appId: '1:228604895992:web:09904dbbc9efa5a2fe110d',
    messagingSenderId: '228604895992',
    projectId: 'coffeeshop-5cae5',
    authDomain: 'coffeeshop-5cae5.firebaseapp.com',
    storageBucket: 'coffeeshop-5cae5.firebasestorage.app',
    measurementId: 'G-4P3Y3DDZ78',
  );
}
